= Fabric8-AMQP - Test case 3

Playing with Apache ActiveMQ Artemis 2.6.0 on OpenShift/Minishift

== Configuring Apache ActiveMQ Artemis

The Docker image is built by downloading the Apache ActiveMQ Artemis archive, extracting it in
a Docker `openjdk:9` image and pushing it in the `fabric8` org in the Openshift container registry.
This process not only creates the `Deployment` resource, but it also generates a `ConfigMap` with the
content of the `apache-artemis/config` directory, whose files will accessible in a volume be mounted in
the `./etc` directory of the broker. This allows for including custom configuration of the addresses and
queues at the deployment time.

In particular, the `broker.xml` file contains the following definition for the `fabric8.foo` address:

```
<address name="fabric8.foo">
    <multicast>
        <queue name="queue1">
            <durable>true</durable>
        </queue>
        <queue name="queue2">
            <durable>true</durable>
        </queue>
    </multicast>
</address>
```

With such a `multicast` configuration, messages sent to the `fabric8.foo` address will be delivered to both `fabric.foo::queue1` and `fabric8.foo::queue2` queues.

```
$ make deploy-activemq-artemis
```


== Building and deploying the publisher

Each new version of the publisher is automatically deployed using an `ImageStream` and a `DeployConfig`.
Building and deploying a new version of the publisher happens with (all at once!)

```
make deploy-publisher
```

== Building and deploying the subscribers

All subscribers share the same code but are configured differently in their DeployConfig.

To avoid repetition among the YAML files, both subscribers are created using the same OpenShift template:

```
# subscriber 1 with 1 replica 
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=1 -p QUEUE_NAME=fabric8.foo::queue1 | oc apply -f -

# subscriber 2 with 2 replicas
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=2 -p QUEUE_NAME=fabric8.foo::queue2 | oc apply -f -
```

The template used above creates both the `ImageStream` and the `DeployConfig` resources for each subscriber. Once this is done, newer versions of the code can be deployed with

```
$ make deploy-subscribers
```

== Checking the results


```
# start the Apache ActiveMQ Artemis-server (previous replicas was set to '0')
$ oc scale deploy/activemq-artemis --replicas=1
deployment "activemq-artemis" scaled

# scale the publisher and subscribers
$ oc scale dc/publisher dc/subscriber1 --replicas=1 && oc scale dc/subscriber2 --replicas=2
deploymentconfig "publisher" scaled
deploymentconfig "subscriber1" scaled
deploymentconfig "subscriber2" scaled
 
$ oc get pods
NAME                               READY     STATUS    RESTARTS   AGE
activemq-artemis-d9997cbcb-26jsb   1/1       Running   1          1d
publisher-123-s7k64                1/1       Running   0          28s
subscriber1-36-l925f               1/1       Running   0          27s
subscriber2-25-h5244               1/1       Running   0          26s
subscriber2-25-scjq7               1/1       Running   0          26s

# check the logs on the publisher
$ oc logs publisher-123-s7k64
INFO[0000] opened connection to `activemq-artemis:61616` and initialized sender to `fabric8.foo`  id=publisher-123-s7k64
INFO[0003] sent message `message #1 (2018-06-13 09:46:56)`  id=publisher-123-s7k64
INFO[0006] sent message `message #2 (2018-06-13 09:46:59)`  id=publisher-123-s7k64
INFO[0009] sent message `message #3 (2018-06-13 09:47:02)`  id=publisher-123-s7k64
INFO[0012] sent message `message #4 (2018-06-13 09:47:05)`  id=publisher-123-s7k64
INFO[0015] sent message `message #5 (2018-06-13 09:47:08)`  id=publisher-123-s7k64
...
^C

# check the logs on subscriber 1
$ oc logs subscriber1-36-l925f
INFO[0000] opened connection to `activemq-artemis:61616` and initialized receiver to `fabric8.foo::queue1`  id=subscriber1-36-l925f
INFO[0001] received msg: message #1 (2018-06-13 09:46:56)  id=subscriber1-36-l925f
INFO[0004] received msg: message #2 (2018-06-13 09:46:59)  id=subscriber1-36-l925f
INFO[0007] received msg: message #3 (2018-06-13 09:47:02)  id=subscriber1-36-l925f
INFO[0010] received msg: message #4 (2018-06-13 09:47:05)  id=subscriber1-36-l925f
INFO[0013] received msg: message #5 (2018-06-13 09:47:08)  id=subscriber1-36-l925f
...
^C

# check the logs on subscriber 2.1
$ oc logs subscriber2-25-h5244
INFO[0000] opened connection to `activemq-artemis:61616` and initialized receiver to `fabric8.foo::queue2`  id=subscriber2-25-h5244
INFO[0000] received msg: message #1 (2018-06-13 09:46:56)  id=subscriber2-25-h5244
INFO[0006] received msg: message #3 (2018-06-13 09:47:02)  id=subscriber2-25-h5244
INFO[0012] received msg: message #5 (2018-06-13 09:47:08)  id=subscriber2-25-h5244
...
^C

# check the logs on subscriber 2.2
$ oc logs subscriber2-25-scjq7
INFO[0000] opened connection to `activemq-artemis:61616` and initialized receiver to `fabric8.foo::queue2`  id=subscriber2-25-scjq7
INFO[0003] received msg: message #2 (2018-06-13 09:46:59)  id=subscriber2-25-scjq7
INFO[0009] received msg: message #4 (2018-06-13 09:47:05)  id=subscriber2-25-scjq7
...
^C
```

=== Conclusion

Messages sent to the `fabric8.foo` address were delivered to both `fabric8.foo::queue1` and `fabric8.foo::queue2` queues, but on the latter, the 2 subscribers were load-balanced, so messages were delivered to a single instance of the subscriber.