= Fabric8-AMQP - Test case 3

Playing with Apache ActiveMQ Artemis 2.6.0 on OpenShift/Minishift

== Configuring Apache ActiveMQ Artemis

The Docker image is built by downloading the Apache ActiveMQ Artemis archive, extracting it in
a Docker `openjdk:9` image and pushing it in the `fabric8` org in the Openshift container registry.
This process not only creates the `Deployment` resource, but it also generates a `ConfigMap` with the
content of the `apache-artemis/config` directory, whose files will accessible in a volume be mounted in
the `./etc` directory of the broker. This allows for including custom configuration of the addresses and
queues at the deployment time.

In particular, the `broker.xml` file contains the following definition for the `fabric8.foo` address:

```
<address name="fabric8.foo">
    <multicast>
        <queue name="queue1">
            <durable>true</durable>
        </queue>
        <queue name="queue2">
            <durable>true</durable>
        </queue>
    </multicast>
</address>
```

With such a `multicast` configuration, messages sent to the `fabric8.foo` address will be delivered to both `fabric.foo::queue1` and `fabric8.foo::queue2` queues.

```
$ make deploy-activemq-artemis
```


== Building and deploying the publisher

Each new version of the publisher is automatically deployed using an `ImageStream` and a `DeployConfig`.
Building and deploying a new version of the publisher happens with (all at once!)

```
make deploy-publisher
```

== Building and deploying the subscribers

All subscribers share the same code but are configured differently in their DeployConfig.

To avoid repetition among the YAML files, both subscribers are created using the same OpenShift template:

```
# subscriber 1 with 1 replica 
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=1 -p QUEUE_NAME=fabric8.foo::queue1 | oc apply -f -

# subscriber 2 with 2 replicas
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=2 -p QUEUE_NAME=fabric8.foo::queue2 | oc apply -f -
```

The template used above creates both the `ImageStream` and the `DeployConfig` resources for each subscriber. Once this is done, newer versions of the code can be deployed with

```
$ make deploy-subscribers
```

== Checking the results


```
# start the Apache ActiveMQ Artemis-server (previous replicas was set to '0')
$ oc scale deploy/activemq-artemis --replicas=1
deployment "activemq-artemis" scaled

$ oc get pods
NAME                               READY     STATUS    RESTARTS   AGE
activemq-artemis-d9997cbcb-gpwd6   1/1       Running   0          3m
publisher-114-mbz8g                1/1       Running   0          5s
subscriber1-28-4p4s9               1/1       Running   0          28s
subscriber2-20-5tg9c               1/1       Running   0          38s
subscriber2-20-zv54m               1/1       Running   0          38s

 
# check the logs on the publisher
$ oc logs publisher-114-mbz8g
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=publisher-114-mbz8g
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=publisher-114-mbz8g
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=publisher-114-mbz8g
INFO[0003] published msg 'message #1 (2018-06-08 10:04:16)' to address 'fabric8.foo'  id=publisher-114-mbz8g
INFO[0006] published msg 'message #2 (2018-06-08 10:04:19)' to address 'fabric8.foo'  id=publisher-114-mbz8g
INFO[0009] published msg 'message #3 (2018-06-08 10:04:22)' to address 'fabric8.foo'  id=publisher-114-mbz8g
INFO[0012] published msg 'message #4 (2018-06-08 10:04:25)' to address 'fabric8.foo'  id=publisher-114-mbz8g
INFO[0015] published msg 'message #5 (2018-06-08 10:04:28)' to address 'fabric8.foo'  id=publisher-114-mbz8g
...
^C

# check the logs on subscriber 1
$ oc logs subscriber1-28-4p4s9
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber1-28-4p4s9
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber1-28-4p4s9
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber1-28-4p4s9
INFO[0000] initialized receiver on 'fabric8.foo::queue1'  id=subscriber1-28-4p4s9
INFO[0026] received msg: message #1 (2018-06-08 10:04:16)  id=subscriber1-28-4p4s9
INFO[0029] received msg: message #2 (2018-06-08 10:04:19)  id=subscriber1-28-4p4s9
INFO[0032] received msg: message #3 (2018-06-08 10:04:22)  id=subscriber1-28-4p4s9
INFO[0035] received msg: message #4 (2018-06-08 10:04:25)  id=subscriber1-28-4p4s9
INFO[0038] received msg: message #5 (2018-06-08 10:04:28)  id=subscriber1-28-4p4s9
...
^C

# check the logs on subscriber 2.1
$ oc logs subscriber2-20-5tg9c
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber2-20-5tg9c
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber2-20-5tg9c
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber2-20-5tg9c
INFO[0000] initialized receiver on 'fabric8.foo::queue2'  id=subscriber2-20-5tg9c
INFO[0035] received msg: message #1 (2018-06-08 10:04:16)  id=subscriber2-20-5tg9c
INFO[0041] received msg: message #3 (2018-06-08 10:04:22)  id=subscriber2-20-5tg9c
INFO[0047] received msg: message #5 (2018-06-08 10:04:28)  id=subscriber2-20-5tg9c
...
^C

# check the logs on subscriber 2.2
$ oc logs subscriber2-20-zv54m
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber2-20-zv54m
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber2-20-zv54m
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber2-20-zv54m
INFO[0000] initialized receiver on 'fabric8.foo::queue2'  id=subscriber2-20-zv54m
INFO[0038] received msg: message #2 (2018-06-08 10:04:19)  id=subscriber2-20-zv54m
INFO[0044] received msg: message #4 (2018-06-08 10:04:25)  id=subscriber2-20-zv54m
...
^C
```

=== Conclusion

Messages sent to the `fabric8.foo` address were delivered to both `fabric8.foo::queue1` and `fabric8.foo::queue2` queues, but on the latter, the 2 subscribers were load-balanced, so messages were delivered to a single instance of the subscriber.