= Fabric8-AMQP - Test case 2

Playing with Apache ActiveMQ Artemis 2.6.0 on OpenShift/Minishift

== Deploying Apache ActiveMQ Artemis

First, the Docker image is built by downloading the Apache ActiveMQ Artemis archive, extracting it in
a Docker `openjdk:9` image and pushing it in the `fabric8` org in the Openshift container registry: 

```
$ make deploy-activemq-artemis
```

== Building and deploying the publisher

Each new version of the publisher is automatically deployed using an `ImageStream` and a `DeployConfig`.
Building and deploying a new version of the publisher happens with (all at once!)

```
make deploy-publisher
```

== Building and deploying the subscribers

All subscribers share the same code but are configured differently in their DeployConfig.

To avoid repetition among the YAML files, both subscribers are created using the same OpenShift template:

```
# subscriber 1 with 0 replica 
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=0 -p TARGET_ADDRESSES=addr1 | oc apply -f -

# subscriber 2 with 0 replica
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=0 -p TARGET_ADDRESSES=addr2 | oc apply -f -
```

The template used above creates both the `ImageStream` and the `DeployConfig` resources for each subscriber. Once this is done, a new version of the code can be deployed with

```
$ make deploy-subscribers
```

== Checking the results


```
# start the Apache ActiveMQ Artemis-server (previous replicas was set to '0')
$ oc scale deploy/activemq-artemis --replicas=1
deployment "activemq-artemis" scaled

 
# start the publisher and subscribers (replica count was previously lowered to '0' to stop all publishing)
$ oc scale dc/publisher dc/subscriber1 dc/subscriber2 --replicas=1
deploymentconfig "publisher" scaled
deploymentconfig "subscriber1" scaled
deploymentconfig "subscriber2" scaled

$ oc get pods
NAME                                READY     STATUS    RESTARTS   AGE
activemq-artemis-8c96dbddb-7xdm2   1/1       Running   0          53m
publisher-94-t9hpl                 1/1       Running   0          11s
subscriber1-8-zbj5z                1/1       Running   0          10s
subscriber2-3-894vq                1/1       Running   0          9s


# check the logs on the publisher
$ oc logs publisher-94-t9hpl
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=publisher-94-t9hpl
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=publisher-94-t9hpl
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=publisher-94-t9hpl
INFO[0003] preparing msg 'message #1                     id=publisher-94-t9hpl
INFO[0003] publishing msg 'message #1'...                id=publisher-94-t9hpl
INFO[0003] published msg 'message #1' to address 'addr1'  id=publisher-94-t9hpl
INFO[0003] published msg 'message #1' to address 'addr2'  id=publisher-94-t9hpl
...
^C

# check the logs on subscriber 1
$ oc logs subscriber1-8-zbj5z
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber1-8-zbj5z
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber1-8-zbj5z
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber1-8-zbj5z
INFO[0001] received msg: message #1                      id=subscriber1-8-zbj5z
...
^C

# check the logs on subscriber 2
$ oc logs subscriber2-3-894vq
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber2-3-894vq
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber2-3-894vq
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber2-3-894vq
INFO[0001] received msg: message #1                      id=subscriber2-3-894vq
INFO[0004] received msg: message #2                      id=subscriber2-3-894vq
INFO[0007] received msg: message #3                      id=subscriber2-3-894vq
INFO[0010] received msg: message #4                      id=subscriber2-3-894vq
...
# kill subscriber 2, let OpenShift schedule another pod
...
INFO[0029] received msg: message #117                    id=subscriber2-3-894vq
INFO[0032] received msg: message #118                    id=subscriber2-3-894vq
INFO[0035] received msg: message #119                    id=subscriber2-3-894vq
rpc error: code = Unknown desc = Error: No such container: fabefd987b0e0d5ece90130239fabd464123b88b91e4b90abfbc9b3474ec6c6c

# check the logs on "new" subscriber 2
$ oc logs subscriber2-3-dtwsz
INFO[0000] opening connection to broker on 'amqp://activemq-artemis:61616'...  id=subscriber2-3-dtwsz
INFO[0000] connection established with server at 'amqp://activemq-artemis:61616'  id=subscriber2-3-dtwsz
INFO[0000] obtained a new session at 'amqp://activemq-artemis:61616'  id=subscriber2-3-dtwsz
INFO[0000] received msg: message #120                    id=subscriber2-3-dtwsz

```


=== Conclusion

When the pod for the subscriber 2 was (hard) deleted, no message was lost.