apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activemq-artemis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq-artemis
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: apache-artemis-cm
      containers:
      - name: activemq-artemis
        image: "fabric8/activemq-artemis:2.6.0"
        command: ["/var/lib/apache-artemis/data/fabric8-broker/bin/artemis"]
        args: ["run"]
        volumeMounts:
        - name: config-volume
          mountPath: /var/lib/apache-artemis/data/fabric8-broker/etc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: activemq-artemis
  name: activemq-artemis
spec:
  ports:
  - name: all-protocols
    port: 61616
    protocol: TCP
    targetPort: 61616
    nodePort: 31616
  - name: amqps
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 31672
  - name: mgmt
    port: 8161
    protocol: TCP
    targetPort: 8161
    nodePort: 31161
  selector:
    app: activemq-artemis
  type: NodePort
---